GET http://localhost:8000/demo/

###

POST http://localhost:8000/demo/

###

GET http://localhost:8000/weapon/3/

###

GET http://localhost:8000/comments/

###
GET http://localhost:8000/adv/

###
POST http://localhost:8000/adv/
Content-Type: application/json
Authorization: Token ec70951f53b04b1a2ea9b3f15cf7623e4d8d4d85
{    
    "text": "Объявление",
}