# Generated by Django 4.1.2 on 2022-10-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='power',
            field=models.IntegerField(),
        ),
    ]
